"use client";
import { useState } from "react";
type Permission={user_id:string;display_name:string;access:"read"|"write"};
export function PermissionsPanel({tableId}:{tableId:string}){const [open,setOpen]=useState(false);const [items,setItems]=useState<Permission[]>([]);const [userId,setUserId]=useState("");const [access,setAccess]=useState<"read"|"write">("read");const [error,setError]=useState("");
  async function load(){const response=await fetch(`/api/tables/${tableId}/permissions`);if(response.ok)setItems(await response.json());}
  async function toggle(){const next=!open;setOpen(next);if(next)await load();}
  async function grant(){if(!confirm(`Grant ${access} access to this table?`))return;setError("");const response=await fetch(`/api/tables/${tableId}/permissions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userId,access,confirmed:true})});if(!response.ok){setError((await response.json()).error??"Sharing failed");return;}setUserId("");await load();}
  async function revoke(id:string){if(!confirm("Revoke this user's access?"))return;const response=await fetch(`/api/tables/${tableId}/permissions/${id}?confirmed=true`,{method:"DELETE"});if(response.ok)await load();}
  return <div className="permissions"><button className="secondary" onClick={toggle}>{open?"Close sharing":"Sharing"}</button>{open&&<section className="permissions-popover"><h2>Table access</h2><div className="grant-row"><input aria-label="User UUID" value={userId} onChange={e=>setUserId(e.target.value)} placeholder="User UUID"/><select aria-label="Access level" value={access} onChange={e=>setAccess(e.target.value as "read"|"write")}><option value="read">Read</option><option value="write">Write</option></select><button disabled={!userId} onClick={grant}>Grant</button></div>{error&&<p className="error">{error}</p>}<ul>{items.map(item=><li key={item.user_id}><div><strong>{item.display_name||item.user_id}</strong><small>{item.access}</small></div><button className="danger" onClick={()=>revoke(item.user_id)}>Revoke</button></li>)}</ul>{!items.length&&<p className="muted">This table is private.</p>}</section>}</div>}
