"use client";
import { useState } from "react";
type Permission={user_id:string;display_name:string;access:"read"|"write"};
type Profile={id:string;display_name:string};
export function PermissionsPanel({tableId}:{tableId:string}){const [open,setOpen]=useState(false);const [items,setItems]=useState<Permission[]>([]);const [profiles,setProfiles]=useState<Profile[]>([]);const [userId,setUserId]=useState("");const [access,setAccess]=useState<"read"|"write">("read");const [error,setError]=useState("");
  async function load(){const [permissionsResponse,profilesResponse]=await Promise.all([fetch(`/api/tables/${tableId}/permissions`),fetch(`/api/tables/${tableId}/profiles`)]);if(permissionsResponse.ok)setItems(await permissionsResponse.json());if(profilesResponse.ok)setProfiles(await profilesResponse.json());}
  async function toggle(){const next=!open;setOpen(next);if(next)await load();}
  async function grant(){if(!confirm(`Grant ${access} access to this table?`))return;setError("");const response=await fetch(`/api/tables/${tableId}/permissions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userId,access,confirmed:true})});if(!response.ok){setError((await response.json()).error??"Sharing failed");return;}setUserId("");await load();}
  async function revoke(id:string){if(!confirm("Revoke this user's access?"))return;const response=await fetch(`/api/tables/${tableId}/permissions/${id}?confirmed=true`,{method:"DELETE"});if(response.ok)await load();}
  return <div className="permissions"><button type="button" className="secondary" onClick={toggle}>{open?"Close sharing":"Share table"}</button>{open&&<section className="permissions-popover"><div className="popover-heading"><div><p className="eyebrow">ACCESS CONTROL</p><h2>Share this table</h2></div><button type="button" className="icon-button" aria-label="Close sharing" onClick={toggle}>×</button></div><p className="muted">Choose an active workspace profile and set what they can do.</p><div className="grant-row"><label><span>Profile</span><select aria-label="Active profile" value={userId} onChange={e=>setUserId(e.target.value)}><option value="">Select a profile</option>{profiles.map(profile=><option key={profile.id} value={profile.id}>{profile.display_name||"Unnamed profile"}</option>)}</select></label><label><span>Access</span><select aria-label="Access level" value={access} onChange={e=>setAccess(e.target.value as "read"|"write")}><option value="read">Can view</option><option value="write">Can edit</option></select></label><button disabled={!userId} onClick={grant}>Share</button></div>{!profiles.length&&<p className="availability-note">There are no other active profiles available to share with.</p>}{error&&<p className="error">{error}</p>}<div className="access-list"><p className="list-label">People with access</p><ul>{items.map(item=><li key={item.user_id}><div className="access-profile"><span>{(item.display_name||"?").slice(0,1).toUpperCase()}</span><div><strong>{item.display_name||"Unnamed profile"}</strong><small>{item.access==="write"?"Can edit":"Can view"}</small></div></div><button type="button" className="danger" onClick={()=>revoke(item.user_id)}>Remove</button></li>)}</ul>{!items.length&&<p className="muted">Only you can access this table right now.</p>}</div></section>}</div>}
