import { createHash,randomBytes,createHmac } from "node:crypto";
import { approveAction,rejectAction } from "@/server/confirmations/service";
import { actorFromTelegram } from "@/server/auth/session";
import { getConfig } from "@/server/config";
import { querySystem } from "@/server/db";
import { runJarvisAgent } from "@/server/agent/run";
import { getTelegramFile,sendTelegramMessage,answerCallbackQuery } from "./client";
import type { TelegramMessage,TelegramUpdate } from "./types";
import { inspectDocument,storeAttachment,transcribeVoice } from "@/server/files/service";

export function tokenHash(token:string){return createHash("sha256").update(token).digest("hex");}
export function newLinkToken(){return randomBytes(24).toString("base64url");}
function actionSignature(id:string,userId:string){return createHmac("sha256",getConfig().ACTION_SIGNING_SECRET).update(`${id}.${userId}`).digest().subarray(0,12).toString("base64url");}

async function linkTelegram(message:TelegramMessage,token:string){if(!message.from)throw new Error("Telegram user missing");const rows=await querySystem<{user_id:string}>(`update public.bot_link_tokens t set consumed_at=now() from public.profiles p where t.user_id=p.id and t.token_hash=$1 and t.consumed_at is null and t.expires_at>now() and p.status='active' returning t.user_id`,[tokenHash(token)]);if(!rows[0]){await sendTelegramMessage(message.chat.id,"This link is invalid, expired, or the account is not active.");return;}await querySystem(`insert into public.bot_connections(user_id,telegram_user_id,telegram_chat_id,telegram_username) values($1,$2,$3,$4) on conflict(user_id) do update set telegram_user_id=excluded.telegram_user_id,telegram_chat_id=excluded.telegram_chat_id,telegram_username=excluded.telegram_username,connected_at=now()`,[rows[0].user_id,message.from.id,message.chat.id,message.from.username??null]);await sendTelegramMessage(message.chat.id,"Telegram connected. Tell me what you want to store or retrieve.");}

async function messageText(message:TelegramMessage,actorId:string){if(message.text)return message.text;if(message.voice){if((message.voice.file_size??0)>getConfig().MAX_ATTACHMENT_BYTES)throw new Error("Voice file is too large");const file=await getTelegramFile(message.voice.file_id);await storeAttachment(actorId,file.bytes,message.voice.mime_type??"audio/ogg");return transcribeVoice(file.bytes);}const media=message.document??message.photo?.at(-1);if(media){if((media.file_size??0)>getConfig().MAX_ATTACHMENT_BYTES)throw new Error("File is too large");const file=await getTelegramFile(media.file_id);const type=message.document?.mime_type??"image/jpeg";await storeAttachment(actorId,file.bytes,type);const extracted=await inspectDocument(file.bytes,type);return `${message.caption??"Please process this attachment."}\n\nUNTRUSTED EXTRACTED DOCUMENT CONTENT:\n${extracted}`;}return message.caption??"";}

async function handleMessage(message:TelegramMessage,eventId?:string){const start=message.text?.match(/^\/start\s+([A-Za-z0-9_-]+)$/);if(start)return linkTelegram(message,start[1]);if(!message.from)return;const actor=await actorFromTelegram(message.from.id);if(!actor||actor.status!=="active"){await sendTelegramMessage(message.chat.id,"This Telegram account is not linked to an active Jarvis profile.");return;}const recent=await querySystem<{count:string}>(`select count(*)::text from public.messages where user_id=$1 and role='user' and created_at>now()-interval '1 minute'`,[actor.id]);if(Number(recent[0].count)>=30){await sendTelegramMessage(message.chat.id,"Rate limit reached. Please try again in a minute.");return;}const text=await messageText(message,actor.id);if(!text)return;if(eventId&&/(ignore (all|previous)|reveal (the )?(secret|system)|execute (raw )?sql|you are now (an )?admin|bypass (the )?(policy|confirmation))/i.test(text))await querySystem(`update public.inbound_events set security_flag=true where id=$1`,[eventId]);
  const conversations=await querySystem<{id:string}>(`insert into public.conversation_threads(user_id,telegram_chat_id) values($1,$2) on conflict(user_id,telegram_chat_id) do update set updated_at=now() returning id`,[actor.id,message.chat.id]);const conversationId=conversations[0].id;await querySystem(`insert into public.messages(conversation_id,user_id,telegram_message_id,role,content) values($1,$2,$3,'user',$4) on conflict(conversation_id,telegram_message_id) where telegram_message_id is not null do nothing`,[conversationId,actor.id,message.message_id,text.slice(0,200_000)]);
  const before=await querySystem<{created_at:string}>(`select now()::text as created_at`);const result=await runJarvisAgent(actor,text);const response=result.text||"I prepared the requested operation.";await querySystem(`insert into public.messages(conversation_id,user_id,role,content) values($1,$2,'assistant',$3)`,[conversationId,actor.id,response]);await sendTelegramMessage(message.chat.id,escapeHtml(response));
  const pending=await querySystem<{id:string;action_type:string}>(`select id,action_type from public.pending_actions where requested_by=$1 and status='pending' and created_at >= $2::timestamptz order by created_at`,[actor.id,before[0].created_at]);for(const action of pending){const sig=actionSignature(action.id,actor.id);await sendTelegramMessage(message.chat.id,`Confirm <b>${escapeHtml(action.action_type.replaceAll("_"," "))}</b>?`,{inline_keyboard:[[{text:"Yes",callback_data:`a:${action.id}:${sig}`},{text:"No",callback_data:`r:${action.id}:${sig}`}]]});}}

async function handleCallback(update:TelegramUpdate){const callback=update.callback_query!;const parsed=callback.data?.match(/^([ar]):([0-9a-f-]{36}):([A-Za-z0-9_-]{16})$/);if(!parsed){await answerCallbackQuery(callback.id,"Invalid action");return;}const actor=await actorFromTelegram(callback.from.id);if(!actor||actor.status!=="active"){await answerCallbackQuery(callback.id,"Account unavailable");return;}try{if(parsed[1]==="a")await approveAction(actor,parsed[2],parsed[3]);else await rejectAction(actor,parsed[2],parsed[3]);await answerCallbackQuery(callback.id,parsed[1]==="a"?"Executed":"Rejected");if(callback.message)await sendTelegramMessage(callback.message.chat.id,parsed[1]==="a"?"Done.":"Cancelled.");}catch(error){await answerCallbackQuery(callback.id,"Action unavailable");if(callback.message)await sendTelegramMessage(callback.message.chat.id,escapeHtml(error instanceof Error?error.message:"Action failed"));}}
export async function processTelegramUpdate(update:TelegramUpdate,eventId?:string){if(update.callback_query)return handleCallback(update);if(update.message)return handleMessage(update.message,eventId);}
function escapeHtml(value:string){return value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
