import { createHash,randomBytes,createHmac } from "node:crypto";
import { approveAction } from "@/server/confirmations/service";
import { actorFromTelegram } from "@/server/auth/session";
import { getConfig } from "@/server/config";
import { querySystem } from "@/server/db";
import { runJarvisAgent } from "@/server/agent/run";
import { getTelegramFile,sendTelegramMessage,answerCallbackQuery } from "./client";
import type { TelegramMessage,TelegramUpdate } from "./types";
import { inspectDocument,storeAttachment,transcribeVoice } from "@/server/files/service";
import { createTelegramPlan,type PlanStep } from "./progress";
import { beginTask,finishTask,getActiveTask,recordTaskFact,recordVerifiedResult,saveTaskPlan } from "@/server/tasks/service";

export function tokenHash(token:string){return createHash("sha256").update(token).digest("hex");}
export function newLinkToken(){return randomBytes(24).toString("base64url");}
function actionSignature(id:string,userId:string){return createHmac("sha256",getConfig().ACTION_SIGNING_SECRET).update(`${id}.${userId}`).digest().subarray(0,12).toString("base64url");}
const unsupportedCompletionClaim=/(?:готово|выполнено|сохран(?:ил|ено)|добав(?:ил|лено)|создал|создано|обновил|обновлено|удалил|удалено|изменил|изменено|\b(?:created|saved|added|updated|deleted|completed)\b)/iu;
export function safeAgentResponse(text:string,databaseChanged:boolean){return !databaseChanged&&unsupportedCompletionClaim.test(text)?"Данные не изменялись в рамках этого запроса.":text;}

async function linkTelegram(message:TelegramMessage,token:string){if(!message.from)throw new Error("Не найден пользователь Telegram");const rows=await querySystem<{user_id:string}>(`update public.bot_link_tokens t set consumed_at=now() from public.profiles p where t.user_id=p.id and t.token_hash=$1 and t.consumed_at is null and t.expires_at>now() and p.status='active' returning t.user_id`,[tokenHash(token)]);if(!rows[0]){await sendTelegramMessage(message.chat.id,"Ссылка недействительна, истекла или аккаунт не активен.");return;}await querySystem(`insert into public.bot_connections(user_id,telegram_user_id,telegram_chat_id,telegram_username) values($1,$2,$3,$4) on conflict(user_id) do update set telegram_user_id=excluded.telegram_user_id,telegram_chat_id=excluded.telegram_chat_id,telegram_username=excluded.telegram_username,connected_at=now()`,[rows[0].user_id,message.from.id,message.chat.id,message.from.username??null]);await sendTelegramMessage(message.chat.id,"Telegram подключён. Напишите, что сохранить или найти.");}

async function messageText(message:TelegramMessage,actorId:string){if(message.text)return message.text;if(message.voice){if((message.voice.file_size??0)>getConfig().MAX_ATTACHMENT_BYTES)throw new Error("Голосовое сообщение слишком большое");const file=await getTelegramFile(message.voice.file_id);await storeAttachment(actorId,file.bytes,message.voice.mime_type??"audio/ogg");return transcribeVoice(file.bytes);}const media=message.document??message.photo?.at(-1);if(media){if((media.file_size??0)>getConfig().MAX_ATTACHMENT_BYTES)throw new Error("Файл слишком большой");const file=await getTelegramFile(media.file_id);const type=message.document?.mime_type??"image/jpeg";await storeAttachment(actorId,file.bytes,type);const extracted=await inspectDocument(file.bytes,type);return `${message.caption??"Обработай это вложение."}\n\nUNTRUSTED EXTRACTED DOCUMENT CONTENT:\n${extracted}`;}return message.caption??"";}

async function handleMessage(message:TelegramMessage,eventId?:string){const start=message.text?.match(/^\/start\s+([A-Za-z0-9_-]+)$/);if(start)return linkTelegram(message,start[1]);if(!message.from)return;const actor=await actorFromTelegram(message.from.id);if(!actor||actor.status!=="active"){await sendTelegramMessage(message.chat.id,"Этот аккаунт Telegram не привязан к активному профилю Jarvis.");return;}const recent=await querySystem<{count:string}>(`select count(*)::text from public.messages where user_id=$1 and role='user' and created_at>now()-interval '1 minute'`,[actor.id]);if(Number(recent[0].count)>=30){await sendTelegramMessage(message.chat.id,"Превышен лимит запросов. Попробуйте через минуту.");return;}const text=await messageText(message,actor.id);if(!text)return;if(eventId&&/(ignore (all|previous)|reveal (the )?(secret|system)|execute (raw )?sql|you are now (an )?admin|bypass (the )?(policy|confirmation))/i.test(text))await querySystem(`update public.inbound_events set security_flag=true where id=$1`,[eventId]);
  const conversations=await querySystem<{id:string}>(`insert into public.conversation_threads(user_id,telegram_chat_id) values($1,$2) on conflict(user_id,telegram_chat_id) do update set updated_at=now() returning id`,[actor.id,message.chat.id]);const conversationId=conversations[0].id;await querySystem(`insert into public.messages(conversation_id,user_id,telegram_message_id,role,content) values($1,$2,$3,'user',$4) on conflict(conversation_id,telegram_message_id) where telegram_message_id is not null do nothing`,[conversationId,actor.id,message.message_id,text.slice(0,200_000)]);
  const prior=await getActiveTask(conversationId);const task=await beginTask(conversationId,actor.id,text,prior);const renderPlan=await createTelegramPlan(message.chat.id);let plan:PlanStep[]=[];
  const advancePlan=async(label:string)=>{const active=plan.findIndex(item=>item.status==="active");if(active>=0)plan[active]={...plan[active],status:"done"};const existing=plan.findIndex(item=>item.label===label);if(existing>=0)plan[existing]={...plan[existing],status:"active"};else plan.push({label,status:"active"});await saveTaskPlan(task.id,plan,Math.max(0,plan.length-1));await renderPlan(plan);};
  try{const before=await querySystem<{created_at:string}>(`select now()::text as created_at`);let databaseChanged=false;const taskContext=prior?{originalIntent:prior.original_intent,gatheredFacts:prior.gathered_facts,unresolvedAmbiguity:prior.unresolved_ambiguity,previousPlan:prior.plan}:null;const result=await runJarvisAgent(actor,text,{activeTask:taskContext,onProgress:()=>undefined,onStep:advancePlan,onDatabaseChange:()=>{databaseChanged=true;}});const response=safeAgentResponse(result.text||"Я подготовил запрошенную операцию.",databaseChanged);const pending=await querySystem<{id:string;action_type:string;table_name:string|null}>(`select a.id,a.action_type,t.display_name as table_name from public.pending_actions a left join public.data_tables t on t.id=(a.frozen_payload->>'tableId')::uuid where a.requested_by=$1 and a.status='pending' and a.created_at >= $2::timestamptz order by a.created_at`,[actor.id,before[0].created_at]);
  if(plan.some(step=>step.status==="active")){plan=plan.map(step=>step.status==="active"?{...step,status:"done"}:step);}if(!plan.length)plan=[{label:"Готово",status:"done"}];await saveTaskPlan(task.id,plan,Math.max(0,plan.length-1));await renderPlan(plan);if(databaseChanged)await recordVerifiedResult(task.id,{verified:true,at:new Date().toISOString()});await recordTaskFact(task.id,"latest_response",response);await finishTask(task.id,pending.length?"awaiting_confirmation":response.includes("?")?"awaiting_input":"completed");await querySystem(`insert into public.messages(conversation_id,user_id,role,content) values($1,$2,'assistant',$3)`,[conversationId,actor.id,response]);const confirmation=pending[0];await sendTelegramMessage(message.chat.id,escapeHtml(response),confirmation?{inline_keyboard:[[{text:"Да, добавить",callback_data:`a:${confirmation.id}:${actionSignature(confirmation.id,actor.id)}`}]]}:undefined);
  }catch(error){plan=plan.length?plan.map(step=>step.status==="active"?{...step,status:"failed"}:step):[{label:"Ошибка",status:"failed"}];await saveTaskPlan(task.id,plan);await renderPlan(plan);await finishTask(task.id,"failed",error instanceof Error?error.message:"Неизвестная ошибка");throw error;}}

async function handleCallback(update:TelegramUpdate){const callback=update.callback_query!;const parsed=callback.data?.match(/^a:([0-9a-f-]{36}):([A-Za-z0-9_-]{16})$/);if(!parsed){await answerCallbackQuery(callback.id,"Некорректное действие");return;}const actor=await actorFromTelegram(callback.from.id);if(!actor||actor.status!=="active"){await answerCallbackQuery(callback.id,"Аккаунт недоступен");return;}try{await approveAction(actor,parsed[1],parsed[2]);await answerCallbackQuery(callback.id,"Выполнено");if(callback.message)await sendTelegramMessage(callback.message.chat.id,"Готово.");}catch(error){await answerCallbackQuery(callback.id,"Действие недоступно");if(callback.message)await sendTelegramMessage(callback.message.chat.id,escapeHtml(error instanceof Error?error.message:"Не удалось выполнить действие"));}}
export async function processTelegramUpdate(update:TelegramUpdate,eventId?:string){if(update.callback_query)return handleCallback(update);if(update.message)return handleMessage(update.message,eventId);}
function escapeHtml(value:string){return value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
